### ISSUE TITLE
extract text from more than 24 pdfs files

### ISSUE THREAD

**Issue by celicoo** [nisaacson/pdf-text-extract#10]
I need to extract text from files 100, but the following error occurs after the file 24:

MacBook-Pro-de-Marcelo:DataScript celicoo$ node bin/www  GFIP\'s\ \(rubricas\)/_/*
/Users/celicoo/LacLaw/DataScript/node_modules/pdf-text-extract/index.js:51
  child.stdout.setEncoding('utf8')
              ^
TypeError: Cannot read property 'setEncoding' of undefined
    at streamResults (/Users/celicoo/LacLaw/DataScript/node_modules/pdf-text-extract/index.js:51:15)
    at pdfTextExtract (/Users/celicoo/LacLaw/DataScript/node_modules/pdf-text-extract/index.js:23:3)
    at Object.Pdf.extract (/Users/celicoo/LacLaw/DataScript/core/extract/Types/pdf.js:15:9)
    at Object.Types.read (/Users/celicoo/LacLaw/DataScript/core/extract/Types/index.js:14:31)
    at Object.Extract.each_file (/Users/celicoo/LacLaw/DataScript/core/extract/index.js:15:19)
    at Object.Extract.check_existence (/Users/celicoo/LacLaw/DataScript/core/extract/index.js:25:14)
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)

Any ideas why? and more important, how to fix?
Thanks.

**Comment by nisaacson** [comment]
Do you still see this issue in version `1.3.1`?

**Comment by celicoo** [comment]
No more, I managed to fix my changing my code to synchronous. The problem is that I was doing a loop to remove text from 600 PDF's, that caused the child process broke due to the asynchronous nature of javascript.

Thanks anyway.
