### ISSUE TITLE
Unhandled errors provide no hint as to the actual problem on command line

### ISSUE THREAD

**Issue by hubrix** [nisaacson/pdf-text-extract#22]
pdf-text-extract XXXXXX.pdf
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn pdftotext ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

**Comment by Simonig** [comment]
Same error here!

**Comment by qualisign** [comment]
Same here

**Comment by ysmarc** [comment]
any solution for this?

**Comment by ulvido** [comment]
same error. why? idk

**Comment by nzhtrtlc** [comment]
same error

**Comment by cgomezmendez** [comment]
Same here

**Comment by nimisis** [comment]
As mentioned in https://www.npmjs.com/package/pdf-text-extract#installation you have to install the pdftotext binary as well to get this to work.
