### ISSUE TITLE
Getting issue with large fies

### ISSUE THREAD

**Issue by Sameerhesta** [nisaacson/pdf-text-extract#35]
Hello,

I am using this package and it is working file for the small files, when is tried it with pdf of 48MB (630+ pages), it is giving errors of **Invalid XRef entry** while extracting the pdf.
 
Complete error:-

`PDF_CLICKABLE ERROR Error: pdf-text-extract command failed: Syntax Error: Invalid XRef entry
Internal Error: xref num 11658 not found but needed, try to reconstruct<0a>
Syntax Error: Invalid XRef entry
Syntax Error: Top-level pages object is wrong type (null)
Command Line Error: Wrong page range given: the first page (1) can not be after the last page (0).

    at ChildProcess.closeHandler (/var/www/html/dokkit-deliver-api/node_modules/pdf-text-extract/index.js:136:17)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:675:12)
`
Is there any limitation of this package of regarding the size of PDF or of number of pages?
Is the any way to fix this issue

**Comment by nandita121189** [comment]
@Sameerhesta Were you able to find the cause of this?
I am also getting similar issue while trying to convert my PDF.
